### ISSUE TITLE
MeshLambertMaterials not showing up (black)

### ISSUE THREAD

**Issue by poshaughnessy** [Izzimach/react-three#19]
Hi again. My latest issue is that MeshLambertMaterials appear completely black?

I've tried messing around with all sorts of things (lighting etc). Now I've simplified it into two test cases in [my demo repo](https://github.com/poshaughnessy/react-three-demo/).

If you run it up, http://localhost:8000 shows the version using ReactTHREE which is broken (the robot is black).

http://localhost:8000/test shows a version using THREE directly which is working (the robot is red).

Any ideas? I'd be very grateful again if you could shed any light (pardon the pun) on this!

**Comment by Izzimach** [comment]
Yeah, the problem is that `react-three` is taking in a number for the light color (such as `0xff0000`) but the light needs an instance of `THREE.Color` to work properly.

I'll add some code to do a proper check/conversion. Until then you can get the lights to work by passing in `new THREE.Color(0xff0000)` or whatever for the light colors.

**Comment by poshaughnessy** [comment]
Excellent, yes that's what I needed - thanks again!
