### ISSUE TITLE
Disabling window.requestAnimationFrame( rapidrender )?

### ISSUE THREAD

**Issue by nadnad** [Izzimach/react-three#28]
Hi there,

I'm wondering about the use of window.requestAnimationFrame( rapidrender ) in THREEScene. In my case I am calling requestAnimationFrame in the parent component, where I'm keeping and mutating state that's then passed down to the react-three <Scene> component as props. This results in renderScene() being called both in rapidrender() and in componentDidUpdate(). If there's a use case for rapidrender() which I'm unaware of, perhaps it could be conditionally disabled?

Really enjoying building things with react-three.

**Comment by Izzimach** [comment]
Yeah, there should really be a `dirtyFlag` or something similar so to avoid double-rendering.

Right now the canvas gets re-rendered every frame even if no props/state we changed. This is because some three.js items like skinned meshes need redrawing every frame even if nothing changed in React props/state. I had originally planned to add a flag that disables the auto-rendering every frame, but apparently it never made it in. I'll leave this open as a request for that feature.

**Comment by nadnad** [comment]
Aha, figured there was a reason for it! I'll see if I can submit a pull request to toggle this behavior.

**Comment by Izzimach** [comment]
closed, ref #29
