### ISSUE TITLE
Background only works with transparent is truthy

### ISSUE THREAD

**Issue by scottcheng** [Izzimach/react-three#57]
```js
this._THREErenderer.setClearColor(props.background, this.props.transparent ? 1 : 0);
```

With [this line](https://github.com/Izzimach/react-three/blob/master/src/components/THREEScene.js#L126) of code, it only sets background color when `this.props.transparent` is truthy, which seems odd to me. The prop `transparent` actually means `opaque`.

On a relevant note, why don't we just have an `alpha` prop and pass it directly to `setClearColor`, without coercing it to 1 or 0?

**Comment by geon** [comment]
Fixed in https://github.com/Izzimach/react-three/pull/58

**Comment by Izzimach** [comment]
Thanks @geon

The prop is true/false since [it is also used as an option when creating the GL context](https://github.com/Izzimach/react-three/blob/master/src/components/THREEScene.js#L77) to enable alpha on the canvas. We can add an 'alpha' prop to override the default 0 or 1 behavior if you need it, but I think we should still require the user to explicitly enable canvas transparency with a `transparency={true}` flag.

**Comment by scottcheng** [comment]
Thanks @geon! This looks great.

Thanks @Izzimach for the explanation -- I was just curious and didn't really need the alpha. :)
